//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataPointSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataPointSet()
        {
            this.DataValue = new HashSet<DataValue>();
        }
    
        public int Id { get; set; }
        public int DeviceId { get; set; }
        public int DataLevelId { get; set; }
        public int Address { get; set; }
        public int Unit { get; set; }
        public string Label { get; set; }
        public int CurrentValue { get; set; }
        public int MinValue { get; set; }
        public int MaxValue { get; set; }
        public int SetValue { get; set; }
        public int CritValue { get; set; }
        public int DangerValue { get; set; }
        public int OffsetValue { get; set; }
        public int DSet { get; set; }
        public int DCritPlus { get; set; }
        public int DCritNegative { get; set; }
        public int DDangerPlus { get; set; }
        public int DDangerNegative { get; set; }
        public int DOffset { get; set; }
    
        public virtual DataLevel DataLevel { get; set; }
        public virtual DeviceSet DeviceSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataValue> DataValue { get; set; }
    }
}
