//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataCollectorEntities : DbContext
    {
        public DataCollectorEntities()
            : base("name=DataCollectorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataLevel> DataLevel { get; set; }
        public virtual DbSet<DataPointSet> DataPointSet { get; set; }
        public virtual DbSet<DataValue> DataValue { get; set; }
        public virtual DbSet<DeviceSet> DeviceSet { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Rapor> Rapor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserPermission> UserPermission { get; set; }
    }
}
