//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaShrinkClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirmaShrinkClient()
        {
            this.FirmaÜrünClient = new HashSet<FirmaÜrünClient>();
        }
    
        public int Id { get; set; }
        public int isemriId { get; set; }
        public int FirmaPaletId { get; set; }
        public int FirmaKoliId { get; set; }
        public string Etiket { get; set; }
    
        public virtual FirmaKoliClient FirmaKoliClient { get; set; }
        public virtual FirmaPaletClient FirmaPaletClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaÜrünClient> FirmaÜrünClient { get; set; }
    }
}
