//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaÜrün
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirmaÜrün()
        {
            this.BildirmTipi = new HashSet<BildirmTipi>();
        }
    
        public decimal Id { get; set; }
        public int isEmriId { get; set; }
        public int PaletID { get; set; }
        public int KoliID { get; set; }
        public int ShrinkID { get; set; }
        public string GTN { get; set; }
        public string SKT { get; set; }
        public long SN { get; set; }
        public string LOT { get; set; }
        public string ShrinkKarekod { get; set; }
        public string KoliKarekod { get; set; }
        public string PaletKarekod { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public int UsersID { get; set; }
        public Nullable<decimal> BildirimID { get; set; }
        public Nullable<int> HataKodu { get; set; }
        public string HataMesajı { get; set; }
        public Nullable<int> SatışID { get; set; }
        public Nullable<byte> MakinaNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BildirmTipi> BildirmTipi { get; set; }
        public virtual İşEmri İşEmri { get; set; }
        public virtual Satış Satış { get; set; }
        public virtual Users Users { get; set; }
    }
}
