//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaÜrünClient
    {
        public decimal Id { get; set; }
        public int isEmriId { get; set; }
        public Nullable<int> FirmaPaletId { get; set; }
        public Nullable<int> FirmaKoliId { get; set; }
        public Nullable<int> FirmaShrinkId { get; set; }
        public string GTN { get; set; }
        public string SKT { get; set; }
        public long SN { get; set; }
        public string LOT { get; set; }
        public string ShrinkKarekod { get; set; }
        public string KoliKarekod { get; set; }
        public string PaletKarekod { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public int MaxShrink { get; set; }
        public int MaxKoli { get; set; }
        public int MaxPalet { get; set; }
        public int UsersID { get; set; }
        public string MakinaNo { get; set; }
    
        public virtual FirmaKoliClient FirmaKoliClient { get; set; }
        public virtual FirmaPaletClient FirmaPaletClient { get; set; }
        public virtual FirmaShrinkClient FirmaShrinkClient { get; set; }
    }
}
