//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITS_ClientEntities : DbContext
    {
        public ITS_ClientEntities()
            : base("name=ITS_ClientEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FirmaKoliClient> FirmaKoliClient { get; set; }
        public virtual DbSet<FirmaPaletClient> FirmaPaletClient { get; set; }
        public virtual DbSet<FirmaShrinkClient> FirmaShrinkClient { get; set; }
        public virtual DbSet<FirmaÜrünClient> FirmaÜrünClient { get; set; }
    }
}
