//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class İşEmri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public İşEmri()
        {
            this.FirmaKoli = new HashSet<FirmaKoli>();
            this.FirmaPalet = new HashSet<FirmaPalet>();
            this.FirmaShrink = new HashSet<FirmaShrink>();
            this.FirmaÜrün = new HashSet<FirmaÜrün>();
        }
    
        public int Id { get; set; }
        public string GTN { get; set; }
        public string SN { get; set; }
        public string LOT { get; set; }
        public System.DateTime SKT { get; set; }
        public bool Durum { get; set; }
        public int firmaid { get; set; }
        public int kameraid { get; set; }
        public int inkjetid { get; set; }
        public int EtiketCihazıId { get; set; }
        public Nullable<int> EtiketId { get; set; }
        public int PLCId { get; set; }
        public int FirmaUrunlerId { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool isSended { get; set; }
        public string MaxSn { get; set; }
        public bool ShrinkEtiketi { get; set; }
        public bool KoliEtiketi { get; set; }
        public bool PaletEtiketi { get; set; }
        public byte MakinaNo { get; set; }
        public int ÜretimMiktarı { get; set; }
        public int ShrinkMiktarı { get; set; }
        public int KoliMiktarı { get; set; }
        public int PaletMiktarı { get; set; }
        public int MaxShrinkID { get; set; }
        public int MaxKoliID { get; set; }
        public int MaxPaletID { get; set; }
        public int MinShrinkID { get; set; }
        public int MinKoliID { get; set; }
        public int MinPaletID { get; set; }
        public bool ihracat { get; set; }
        public Nullable<System.DateTime> MFG { get; set; }
    
        public virtual EtiketCihazı EtiketCihazı { get; set; }
        public virtual Etiketler Etiketler { get; set; }
        public virtual Firma Firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaKoli> FirmaKoli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaPalet> FirmaPalet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaShrink> FirmaShrink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaÜrün> FirmaÜrün { get; set; }
        public virtual inkjet inkjet { get; set; }
        public virtual Kamera Kamera { get; set; }
        public virtual PLC PLC { get; set; }
        public virtual Ürünler Ürünler { get; set; }
    }
}
