//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rapor
    {
        public int Id { get; set; }
        public string Bölge { get; set; }
        public int Isı { get; set; }
        public int Nem { get; set; }
        public System.DateTime Tarih { get; set; }
    }
}
