//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satış
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Satış()
        {
            this.FirmaKoli = new HashSet<FirmaKoli>();
            this.FirmaÜrün = new HashSet<FirmaÜrün>();
            this.Transfer = new HashSet<Transfer>();
        }
    
        public int Id { get; set; }
        public System.DateTime Tarih { get; set; }
        public int MerkezDepoID { get; set; }
        public bool Durumu { get; set; }
        public int ÜretimFirmaID { get; set; }
        public string SiparişNo { get; set; }
        public int AlıcıŞubeID { get; set; }
    
        public virtual EczaDeposu EczaDeposu { get; set; }
        public virtual EczaDeposu EczaDeposu1 { get; set; }
        public virtual Firma Firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaKoli> FirmaKoli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaÜrün> FirmaÜrün { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfer { get; set; }
    }
}
