//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool Raporlama { get; set; }
        public bool Asansör { get; set; }
        public bool Alarm { get; set; }
        public bool Ayarlar { get; set; }
        public bool Aydınlatma { get; set; }
    
        public virtual User User { get; set; }
    }
}
