//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.Wcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PLC", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHost.Asansor")]
    [System.SerializableAttribute()]
    public partial class PLC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfClient.Wcf.PLC.KapıDurumları DepoKapıDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HepsiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat1_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat1_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat1_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat1_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat1_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat1_6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat2_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat2_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat2_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat2_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat2_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat2_6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat2_7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat3_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat3_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat3_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat3_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat3_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Kat3_6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfClient.Wcf.PLC.KapıDurumları ZeminKapıDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isConnectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfClient.Wcf.PLC.KapıDurumları ÇatıKapıDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfClient.Wcf.PLC.KapıDurumları İmalatKapıDurumuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfClient.Wcf.PLC.KapıDurumları DepoKapıDurumu {
            get {
                return this.DepoKapıDurumuField;
            }
            set {
                if ((this.DepoKapıDurumuField.Equals(value) != true)) {
                    this.DepoKapıDurumuField = value;
                    this.RaisePropertyChanged("DepoKapıDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Hepsi {
            get {
                return this.HepsiField;
            }
            set {
                if ((this.HepsiField.Equals(value) != true)) {
                    this.HepsiField = value;
                    this.RaisePropertyChanged("Hepsi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1 {
            get {
                return this.Kat1Field;
            }
            set {
                if ((this.Kat1Field.Equals(value) != true)) {
                    this.Kat1Field = value;
                    this.RaisePropertyChanged("Kat1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_1 {
            get {
                return this.Kat1_1Field;
            }
            set {
                if ((this.Kat1_1Field.Equals(value) != true)) {
                    this.Kat1_1Field = value;
                    this.RaisePropertyChanged("Kat1_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_2 {
            get {
                return this.Kat1_2Field;
            }
            set {
                if ((this.Kat1_2Field.Equals(value) != true)) {
                    this.Kat1_2Field = value;
                    this.RaisePropertyChanged("Kat1_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_3 {
            get {
                return this.Kat1_3Field;
            }
            set {
                if ((this.Kat1_3Field.Equals(value) != true)) {
                    this.Kat1_3Field = value;
                    this.RaisePropertyChanged("Kat1_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_4 {
            get {
                return this.Kat1_4Field;
            }
            set {
                if ((this.Kat1_4Field.Equals(value) != true)) {
                    this.Kat1_4Field = value;
                    this.RaisePropertyChanged("Kat1_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_5 {
            get {
                return this.Kat1_5Field;
            }
            set {
                if ((this.Kat1_5Field.Equals(value) != true)) {
                    this.Kat1_5Field = value;
                    this.RaisePropertyChanged("Kat1_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat1_6 {
            get {
                return this.Kat1_6Field;
            }
            set {
                if ((this.Kat1_6Field.Equals(value) != true)) {
                    this.Kat1_6Field = value;
                    this.RaisePropertyChanged("Kat1_6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2 {
            get {
                return this.Kat2Field;
            }
            set {
                if ((this.Kat2Field.Equals(value) != true)) {
                    this.Kat2Field = value;
                    this.RaisePropertyChanged("Kat2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_1 {
            get {
                return this.Kat2_1Field;
            }
            set {
                if ((this.Kat2_1Field.Equals(value) != true)) {
                    this.Kat2_1Field = value;
                    this.RaisePropertyChanged("Kat2_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_2 {
            get {
                return this.Kat2_2Field;
            }
            set {
                if ((this.Kat2_2Field.Equals(value) != true)) {
                    this.Kat2_2Field = value;
                    this.RaisePropertyChanged("Kat2_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_3 {
            get {
                return this.Kat2_3Field;
            }
            set {
                if ((this.Kat2_3Field.Equals(value) != true)) {
                    this.Kat2_3Field = value;
                    this.RaisePropertyChanged("Kat2_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_4 {
            get {
                return this.Kat2_4Field;
            }
            set {
                if ((this.Kat2_4Field.Equals(value) != true)) {
                    this.Kat2_4Field = value;
                    this.RaisePropertyChanged("Kat2_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_5 {
            get {
                return this.Kat2_5Field;
            }
            set {
                if ((this.Kat2_5Field.Equals(value) != true)) {
                    this.Kat2_5Field = value;
                    this.RaisePropertyChanged("Kat2_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_6 {
            get {
                return this.Kat2_6Field;
            }
            set {
                if ((this.Kat2_6Field.Equals(value) != true)) {
                    this.Kat2_6Field = value;
                    this.RaisePropertyChanged("Kat2_6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat2_7 {
            get {
                return this.Kat2_7Field;
            }
            set {
                if ((this.Kat2_7Field.Equals(value) != true)) {
                    this.Kat2_7Field = value;
                    this.RaisePropertyChanged("Kat2_7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3 {
            get {
                return this.Kat3Field;
            }
            set {
                if ((this.Kat3Field.Equals(value) != true)) {
                    this.Kat3Field = value;
                    this.RaisePropertyChanged("Kat3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_1 {
            get {
                return this.Kat3_1Field;
            }
            set {
                if ((this.Kat3_1Field.Equals(value) != true)) {
                    this.Kat3_1Field = value;
                    this.RaisePropertyChanged("Kat3_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_2 {
            get {
                return this.Kat3_2Field;
            }
            set {
                if ((this.Kat3_2Field.Equals(value) != true)) {
                    this.Kat3_2Field = value;
                    this.RaisePropertyChanged("Kat3_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_3 {
            get {
                return this.Kat3_3Field;
            }
            set {
                if ((this.Kat3_3Field.Equals(value) != true)) {
                    this.Kat3_3Field = value;
                    this.RaisePropertyChanged("Kat3_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_4 {
            get {
                return this.Kat3_4Field;
            }
            set {
                if ((this.Kat3_4Field.Equals(value) != true)) {
                    this.Kat3_4Field = value;
                    this.RaisePropertyChanged("Kat3_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_5 {
            get {
                return this.Kat3_5Field;
            }
            set {
                if ((this.Kat3_5Field.Equals(value) != true)) {
                    this.Kat3_5Field = value;
                    this.RaisePropertyChanged("Kat3_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kat3_6 {
            get {
                return this.Kat3_6Field;
            }
            set {
                if ((this.Kat3_6Field.Equals(value) != true)) {
                    this.Kat3_6Field = value;
                    this.RaisePropertyChanged("Kat3_6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfClient.Wcf.PLC.KapıDurumları ZeminKapıDurumu {
            get {
                return this.ZeminKapıDurumuField;
            }
            set {
                if ((this.ZeminKapıDurumuField.Equals(value) != true)) {
                    this.ZeminKapıDurumuField = value;
                    this.RaisePropertyChanged("ZeminKapıDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isConnected {
            get {
                return this.isConnectedField;
            }
            set {
                if ((this.isConnectedField.Equals(value) != true)) {
                    this.isConnectedField = value;
                    this.RaisePropertyChanged("isConnected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfClient.Wcf.PLC.KapıDurumları ÇatıKapıDurumu {
            get {
                return this.ÇatıKapıDurumuField;
            }
            set {
                if ((this.ÇatıKapıDurumuField.Equals(value) != true)) {
                    this.ÇatıKapıDurumuField = value;
                    this.RaisePropertyChanged("ÇatıKapıDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfClient.Wcf.PLC.KapıDurumları İmalatKapıDurumu {
            get {
                return this.İmalatKapıDurumuField;
            }
            set {
                if ((this.İmalatKapıDurumuField.Equals(value) != true)) {
                    this.İmalatKapıDurumuField = value;
                    this.RaisePropertyChanged("İmalatKapıDurumu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="PLC.KapıDurumları", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHost.Asansor")]
        public enum KapıDurumları : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            boşta = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Açılıyor = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Kapanıyor = 2,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf.IAsansor", CallbackContract=typeof(WcfClient.Wcf.IAsansorCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAsansor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsansor/ClientReg", ReplyAction="http://tempuri.org/IAsansor/ClientRegResponse")]
        void ClientReg();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsansorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsansor/AsansörCycleHandler")]
        void AsansörCycleHandler(WcfClient.Wcf.PLC plc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsansorChannel : WcfClient.Wcf.IAsansor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsansorClient : System.ServiceModel.DuplexClientBase<WcfClient.Wcf.IAsansor>, WcfClient.Wcf.IAsansor {
        
        public AsansorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AsansorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AsansorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AsansorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AsansorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ClientReg() {
            base.Channel.ClientReg();
        }
    }
}
